# Generated by Django 3.2.16 on 2023-11-28 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0007_alter_usercommentrelations_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='owner',
        ),
    ]
